title: Aqua GitHub Pages
description: A GitHub Pages site for automating experimental optics with sample efficient machine learning methods.
remote_theme: pages-themes/midnight@v0.2.0
markdown: kramdown
css: assets/style.css
baseurl: ""
url: "https://arindam5aha.github.io/aqua"
author:
  name: "Arindam Saha"
  email: "arindam.saha@anu.edu.au"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
exclude:
  - README.md
